name: Node.js CI

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "12.22.12"
      - name: Fetch Bing wallerpaper
        run: node index.js
      - name: Commit files
        run: |
          git config --local user.email "ocean7hy@gmail.com"
          git config --local user.name "naecoo"
          git pull
          git add README.md
          git commit -m "update README"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
